### ISSUE TITLE
Modify the folder structure.

### ISSUE THREAD

**Issue by ltdrdata** [MokkaBoss1/ComfyUI-Mokkaboss1#1]
1. Move content in `ComfyUI-MokkaBoss1` to root.
`__init__.py` should be placed in root of repo. If not, it cannot be managed simply by `git clone`.

2. Remove `__pycache__` from repo.
cache file should not be included into repo.

Due to the aforementioned issue, I have currently moved this custom nodes to the dev channel.

**Comment by MokkaBoss1** [comment]
many thanks - it's my first time.

Have made the changes as stated.

Kind regards

MokkaBoss1
